package WssCalculator;

/**
* WssCalculator/CalcHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* Sunday, 21 May, 2023 3:53:14 PM IST
*/

public final class CalcHolder implements org.omg.CORBA.portable.Streamable
{
  public WssCalculator.Calc value = null;

  public CalcHolder ()
  {
  }

  public CalcHolder (WssCalculator.Calc initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WssCalculator.CalcHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WssCalculator.CalcHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WssCalculator.CalcHelper.type ();
  }

}
